
-- Shows each customer's current outstanding balance: the total price of
-- lessons that are completed but not yet paid for. Customers with no
-- lessons or no outstanding lessons will show 0.
CREATE OR REPLACE VIEW "Customer_Balances" AS
SELECT
  c.customer_id,
  c.first_name || ' ' || c.last_name AS customer_name,
  c.email_address,
  c.phone_number,
  COALESCE(l.total_charged, 0) - COALESCE(p.total_paid, 0) AS amount_outstanding
FROM "Customers" c
LEFT JOIN (
  SELECT customer_id, SUM(price) AS total_charged
  FROM "Lessons"
  WHERE lesson_status_code = 'COMP'
  GROUP BY customer_id
) l ON l.customer_id = c.customer_id
LEFT JOIN (
  SELECT customer_id, SUM(amount_payment) AS total_paid
  FROM "Customer_Payments"
  GROUP BY customer_id
) p ON p.customer_id = c.customer_id;


-- Lists all future, upcoming booked lessions along with customer, instructor,
-- vehicle, and lesson type details. 
CREATE OR REPLACE VIEW "Upcoming_Lessons" AS
SELECT
  l.lesson_id,
  l.lesson_datetime,
  lt.lesson_name,
  l.price,
  l.lesson_status_code,
  ls.lesson_status_description,
  c.customer_id,
  c.first_name || ' ' || c.last_name   AS customer_name,
  c.phone_number                        AS customer_phone,
  s.staff_id,
  s.first_name || ' ' || s.last_name   AS instructor_name,
  v.make || ' ' || v.model || ' (' || v.year::text || ')' AS vehicle,
  v.registration_plate
FROM       "Lessons"      l
JOIN       "Customers"    c  ON c.customer_id    = l.customer_id
JOIN       "Staff"        s  ON s.staff_id       = l.staff_id
JOIN       "Vehicles"     v  ON v.vehicle_id     = l.vehicle_id
JOIN       "Lesson_Types" lt ON lt.lesson_type_id = l.lesson_type_id
JOIN       "Lesson_Status" ls ON ls.lesson_status_code = l.lesson_status_code
WHERE l.lesson_datetime > NOW()
  AND l.lesson_status_code  IN ('BOOKED');


-- Schedule of instructors, all their lessons (past, present, and future).
CREATE OR REPLACE VIEW  "Staff_Schedule" AS
SELECT
  s.staff_id,
  s.first_name || ' ' || s.last_name   AS instructor_name,
  l.lesson_id,
  l.lesson_datetime,
  lt.lesson_name,
  c.first_name || ' ' || c.last_name   AS customer_name,
  v.make || ' ' || v.model             AS vehicle,
  v.registration_plate,
  ls.lesson_status_description
FROM       "Staff"        s
JOIN       "Lessons"      l  ON l.staff_id       = s.staff_id
JOIN       "Customers"    c  ON c.customer_id    = l.customer_id
JOIN       "Vehicles"     v  ON v.vehicle_id     = l.vehicle_id
JOIN       "Lesson_Types" lt ON lt.lesson_type_id = l.lesson_type_id
JOIN       "Lesson_Status" ls ON ls.lesson_status_code = l.lesson_status_code
ORDER BY s.staff_id, l.lesson_datetime;


-- A record of all payments made by customers, including
-- which payment method was used.
CREATE OR REPLACE VIEW "Customer_Payment_History" AS
SELECT
  cp.payment_id,
  cp.datetime_payment,
  c.customer_id,
  c.first_name || ' ' || c.last_name   AS customer_name,
  pm.payment_method_description,
  cp.amount_payment,
  cp.other_payment_details
FROM       "Customer_Payments" cp
JOIN       "Customers"         c  ON c.customer_id       = cp.customer_id
JOIN       "Payment_Methods"   pm ON pm.payment_method_code = cp.payment_method_code
ORDER BY cp.datetime_payment DESC;



-- Summarises revenue generated by each lesson type, based only on
-- completed lessons. Shows how many were completed,  and total revenue
CREATE OR REPLACE VIEW  "Revenue_By_Lesson_Type" AS
SELECT
  lt.lesson_name,
  COUNT(l.lesson_id)   AS lessons_completed,
  SUM(l.price)         AS total_revenue,
  ROUND(AVG(l.price), 2) AS avg_price
FROM       "Lessons"      l
JOIN       "Lesson_Types" lt ON lt.lesson_type_id = l.lesson_type_id
WHERE l.lesson_status_code = 'COMP'
GROUP BY lt.lesson_name
ORDER BY total_revenue DESC;




